# AI Company in a Box - AWS Infrastructure
# Generated by DevOps Agent

terraform {
  required_version = ">= 1.6.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  backend "s3" {
    bucket = "ai-org-terraform-state"
    key    = "production/terraform.tfstate"
    region = var.aws_region
    encrypt = true
  }
}

provider "aws" {
  region = var.aws_region
  default_tags {
    tags = {
      Project     = "ai-org"
      Environment = var.environment
      ManagedBy   = "AI-Company-in-a-Box"
      Generation  = "Autonomous"
    }
  }
}

locals {
  name_prefix = "ai-org-${var.environment}"
  common_tags = {
    Project     = "ai-org"
    Environment = var.environment
  }
}