#!/usr/bin/env bash
# deploy.sh - Manual AWS Deployment Script
# Generated by DevOps Agent - AI Company in a Box
set -euo pipefail

PROJECT="ai-org"
REGION="us-east-1"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
ECR_BASE="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com"
COMMIT=$(git rev-parse --short HEAD)

echo "Deploying $PROJECT @ $COMMIT"

# Login to ECR
aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_BASE

# Build and push backend
echo "Building backend..."
docker build -t $ECR_BASE/$PROJECT-backend:$COMMIT ./backend
docker push $ECR_BASE/$PROJECT-backend:$COMMIT
docker tag $ECR_BASE/$PROJECT-backend:$COMMIT $ECR_BASE/$PROJECT-backend:latest

# Build and push frontend
echo "Building frontend..."
docker build -t $ECR_BASE/$PROJECT-frontend:$COMMIT ./frontend
docker push $ECR_BASE/$PROJECT-frontend:$COMMIT

# Terraform apply
echo "Applying Terraform..."
cd terraform
terraform init -upgrade
terraform apply -auto-approve \
  -var="backend_image=$ECR_BASE/$PROJECT-backend:$COMMIT" \
  -var="frontend_image=$ECR_BASE/$PROJECT-frontend:$COMMIT"

# Wait for ECS service to stabilize
echo "⏳ Waiting for ECS service..."
aws ecs wait services-stable \
  --cluster "$PROJECT-production-cluster" \
  --services "$PROJECT-production-backend"

# Health check
ALB=$(terraform output -raw alb_dns_name)
echo "🏥 Health check: https://$ALB/health"
curl -sf "https://$ALB/health" && echo "Deployment successful!"