# Build Stage
FROM golang:1.24-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /go/bin/ws-hub ./cmd/ws-hub/

# Final Stage
FROM alpine:latest

# Install runtime dependencies for health checks and HTTPS
RUN apk add --no-cache ca-certificates wget

# Copy the static binary
COPY --from=builder /go/bin/ws-hub /ws-hub

EXPOSE 8081

ENTRYPOINT ["/ws-hub"]

