"""
Mock LLM Client for SARANG demos.
Returns realistic research-style responses when Gemini keys are exhausted.
Mimics the google.genai.Client interface exactly.
"""

MOCK_RESPONSES = {
    "default": """## Research Analysis

Based on my analysis of your query, here are the key findings:

### Key Insights
1. **Primary Finding**: The research domain you've referenced shows significant recent activity, with multiple peer-reviewed publications in the last 12 months.
2. **Methodology Note**: Current state-of-the-art approaches leverage transformer-based architectures with attention mechanisms.
3. **Open Questions**: Reproducibility remains a challenge — only ~35% of published results include full experimental configurations.

### Recommended Next Steps
- Review the latest arXiv preprints for updated benchmarks
- Cross-reference with established datasets (e.g., MMLU, HumanEval)
- Consider running ablation studies to isolate key variables

> **SARANG Confidence**: Medium-High — further peer review recommended.

*This response was generated by the SARANG Research Swarm (Demo Mode).*
"""
}


class MockResponse:
    """Mimics the Gemini response object — just needs a .text attribute."""
    def __init__(self, text: str):
        self.text = text


class MockModels:
    """Mimics genai.Client().models with a generate_content method."""
    def generate_content(self, model: str = "", contents: list = None):
        # Extract user message from the contents payload
        user_msg = ""
        try:
            user_msg = contents[0]["parts"][0]["text"]
        except Exception:
            pass

        return MockResponse(MOCK_RESPONSES["default"])


class MockLLMClient:
    """Drop-in replacement for google.genai.Client.
    Used automatically when all Gemini API keys are exhausted (429).
    """
    def __init__(self):
        self.models = MockModels()

    def __repr__(self):
        return "<MockLLMClient (SARANG Demo Mode)>"
